//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  Machine:  JWHSJIA-PC
//  DateTime: 2017-03-26 오후 11:43:41
//  UserName: JWHSJIA
//  GPLEX input file <scanner.lex - 2017-03-26 오후 11:43:35>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, parser, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, embedbuffers
//  Fallback code page: Target machine default
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;


namespace M11J1
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     public abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     public interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     public sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     public sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 196;
        const int initial = 197;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
/*3.10.2. Floating-Point Literals*/
/*3.10.2. Floating-Point Literals*/
/* 3.10.1 DecimalIntegerLiteral */
/* 3.10.1 HexIntegerLiteral */
/* 3.10.1 OctalIntegerLiteral */
/* 3.10.1 BinaryIntegerLiteral */
/* 3.8 Identifier */
/* hiral*/
int lines = 0;
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {197, 0};

#region CompressedCharacterMap
    //
    // There are 68 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 127 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[127] {
/*     '\0' */ 38, 38, 38, 38, 38, 38, 38, 38, 38, 40, 39, 38, 38, 0, 38, 38, 
/*   '\x10' */ 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 
/*   '\x20' */ 40, 60, 36, 38, 38, 67, 64, 34, 47, 48, 42, 43, 54, 63, 44, 41, 
/*      '0' */ 25, 28, 37, 37, 32, 32, 32, 32, 26, 26, 56, 53, 58, 57, 59, 62, 
/*      '@' */ 55, 30, 33, 30, 30, 45, 30, 38, 38, 38, 38, 38, 29, 38, 38, 38, 
/*      'P' */ 46, 38, 38, 38, 38, 38, 38, 38, 31, 38, 38, 51, 35, 52, 66, 27, 
/*      '`' */ 38, 1, 2, 6, 16, 7, 17, 20, 13, 14, 38, 11, 9, 18, 10, 8, 
/*      'p' */ 21, 38, 5, 3, 4, 15, 22, 23, 19, 12, 24, 49, 65, 50, 61 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 127) // '\0' <= code <= '~'
        return mapC0[code - 0];
      else // '\x7F' <= code <= '\U0010FFFF'
        return (sbyte)38;
    }
#endregion

    static Table[] NxS = new Table[370] {
/* NxS[   0] */ new Table(0, 0, 0, null),
/* NxS[   1] */ new Table(0, 0, -1, null),
/* NxS[   2] */ new Table(1, 46, 80, new short[] {95, 192, 193, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[   3] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 186, 95, 
          95, 187, 80, 80, 80, 188, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[   4] */ new Table(4, 20, -1, new short[] {327, -1, -1, -1, -1, -1, 
          -1, -1, 328, 329, -1, 330, -1, -1, -1, -1, -1, -1, -1, 331}),
/* NxS[   5] */ new Table(5, 9, -1, new short[] {316, -1, -1, -1, -1, -1, 
          -1, -1, 317}),
/* NxS[   6] */ new Table(7, 1, -1, new short[] {312}),
/* NxS[   7] */ new Table(1, 46, 80, new short[] {162, 95, 80, 80, 80, 95, 
          95, 163, 164, 80, 80, 80, 165, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[   8] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 156, 157, 80, 80, 80, 80, 80, 95, 95, 80, 158, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[   9] */ new Table(0, 0, -1, null),
/* NxS[  10] */ new Table(8, 1, -1, new short[] {294}),
/* NxS[  11] */ new Table(1, 7, -1, new short[] {289, -1, -1, -1, -1, -1, 
          290}),
/* NxS[  12] */ new Table(10, 9, -1, new short[] {266, -1, -1, -1, -1, -1, 
          -1, 147, 267}),
/* NxS[  13] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          140, 141, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[  14] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 133, 134, 80, 80, 80, 80, 135, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[  15] */ new Table(8, 1, -1, new short[] {255}),
/* NxS[  16] */ new Table(1, 15, -1, new short[] {235, -1, -1, -1, 236, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 237}),
/* NxS[  17] */ new Table(8, 1, -1, new short[] {228}),
/* NxS[  18] */ new Table(13, 1, -1, new short[] {225}),
/* NxS[  19] */ new Table(1, 46, 58, new short[] {97, 116, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 115, 58, 78, 58, 
          58, 58, 113, 114, 123, 113, 101, 97, 115, 113, 116, 58, 58, 58, 113, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[  20] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 99, 99, 100, 99, 101, 97, 58, 99, 97, 58, 58, 58, 99, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[  21] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[  22] */ new Table(35, 34, 211, new short[] {212, 211, 211, 211, -1, 211, 
          211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 
          211, 211, 211, 211, 211, 211, 211, 211, 211, 211, 211, -1}),
/* NxS[  23] */ new Table(0, 0, -1, null),
/* NxS[  24] */ new Table(41, 17, -1, new short[] {90, 208, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 91}),
/* NxS[  25] */ new Table(57, 1, -1, new short[] {89}),
/* NxS[  26] */ new Table(25, 33, -1, new short[] {198, 198, -1, 198, -1, -1, 
          -1, 198, -1, -1, -1, -1, 198, -1, -1, -1, -1, -1, 87, 199, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 88}),
/* NxS[  27] */ new Table(1, 45, -1, new short[] {203, 203, -1, -1, -1, 203, 
          203, -1, -1, -1, -1, -1, -1, -1, -1, 203, 203, -1, -1, -1, -1, -1, 
          -1, -1, 204, 204, -1, 204, -1, 203, -1, 204, 203, -1, -1, -1, 204, -1, 
          -1, -1, -1, -1, -1, 205, 203}),
/* NxS[  28] */ new Table(0, 0, -1, null),
/* NxS[  29] */ new Table(0, 0, -1, null),
/* NxS[  30] */ new Table(0, 0, -1, null),
/* NxS[  31] */ new Table(0, 0, -1, null),
/* NxS[  32] */ new Table(0, 0, -1, null),
/* NxS[  33] */ new Table(0, 0, -1, null),
/* NxS[  34] */ new Table(0, 0, -1, null),
/* NxS[  35] */ new Table(0, 0, -1, null),
/* NxS[  36] */ new Table(0, 0, -1, null),
/* NxS[  37] */ new Table(56, 1, -1, new short[] {74}),
/* NxS[  38] */ new Table(57, 1, -1, new short[] {73}),
/* NxS[  39] */ new Table(57, 2, -1, new short[] {70, 71}),
/* NxS[  40] */ new Table(57, 3, -1, new short[] {65, -1, 66}),
/* NxS[  41] */ new Table(57, 1, -1, new short[] {64}),
/* NxS[  42] */ new Table(0, 0, -1, null),
/* NxS[  43] */ new Table(0, 0, -1, null),
/* NxS[  44] */ new Table(25, 39, -1, new short[] {198, 198, -1, 198, -1, -1, 
          -1, 198, -1, -1, -1, -1, 198, -1, -1, -1, -1, -1, -1, 199, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 55, -1, 56, -1, -1, -1, 
          57}),
/* NxS[  45] */ new Table(57, 8, -1, new short[] {53, -1, -1, -1, -1, -1, 
          -1, 54}),
/* NxS[  46] */ new Table(57, 9, -1, new short[] {51, -1, -1, -1, -1, -1, 
          -1, -1, 52}),
/* NxS[  47] */ new Table(57, 1, -1, new short[] {50}),
/* NxS[  48] */ new Table(57, 1, -1, new short[] {49}),
/* NxS[  49] */ new Table(0, 0, -1, null),
/* NxS[  50] */ new Table(0, 0, -1, null),
/* NxS[  51] */ new Table(0, 0, -1, null),
/* NxS[  52] */ new Table(0, 0, -1, null),
/* NxS[  53] */ new Table(0, 0, -1, null),
/* NxS[  54] */ new Table(0, 0, -1, null),
/* NxS[  55] */ new Table(0, 0, -1, null),
/* NxS[  56] */ new Table(0, 0, -1, null),
/* NxS[  57] */ new Table(0, 0, -1, null),
/* NxS[  58] */ new Table(0, 0, -1, null),
/* NxS[  59] */ new Table(25, 39, -1, new short[] {201, 201, -1, 201, -1, -1, 
          -1, 201, -1, -1, -1, -1, 201, -1, -1, -1, -1, -1, 202, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          202}),
/* NxS[  60] */ new Table(7, 39, 58, new short[] {59, 58, 58, 58, 58, 58, 
          58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 60, 60, 58, 60, 
          58, 58, 58, 60, 58, 58, 58, 58, 60, 58, -1, 58, 58, 58, 58, 58, 
          59}),
/* NxS[  61] */ new Table(25, 15, 58, new short[] {61, 61, 58, 61, 58, 58, 
          58, 61, 58, 58, 58, 58, 61, 58, -1}),
/* NxS[  62] */ new Table(7, 39, 58, new short[] {59, 58, 58, 58, 58, 58, 
          58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 62, 62, 58, 62, 
          58, 58, 58, 62, 58, 58, 58, 58, 62, 58, -1, 58, 58, 58, 58, 63, 
          59}),
/* NxS[  63] */ new Table(25, 13, -1, new short[] {200, 200, -1, 200, -1, -1, 
          -1, 200, -1, -1, -1, -1, 200}),
/* NxS[  64] */ new Table(0, 0, -1, null),
/* NxS[  65] */ new Table(0, 0, -1, null),
/* NxS[  66] */ new Table(57, 3, -1, new short[] {67, -1, 68}),
/* NxS[  67] */ new Table(0, 0, -1, null),
/* NxS[  68] */ new Table(57, 1, -1, new short[] {69}),
/* NxS[  69] */ new Table(0, 0, -1, null),
/* NxS[  70] */ new Table(0, 0, -1, null),
/* NxS[  71] */ new Table(57, 1, -1, new short[] {72}),
/* NxS[  72] */ new Table(0, 0, -1, null),
/* NxS[  73] */ new Table(0, 0, -1, null),
/* NxS[  74] */ new Table(0, 0, -1, null),
/* NxS[  75] */ new Table(0, 0, -1, null),
/* NxS[  76] */ new Table(1, 46, 80, new short[] {82, 82, 80, 80, 80, 82, 
          82, 80, 80, 80, 80, 80, 80, 80, 80, 82, 82, 80, 80, 80, 83, 80, 
          80, 80, 82, 82, 80, 82, 80, 82, 80, 82, 82, 80, 80, 80, 82, 80, 
          -1, 80, 80, 80, 80, 80, 82, 83}),
/* NxS[  77] */ new Table(63, 52, 80, new short[] {85, 80, 80, 80, 80, 80, 
          82, 82, 80, 80, 80, 82, 82, 80, 80, 80, 80, 80, 80, 80, 80, 82, 
          82, 80, 80, 80, 83, 80, 80, 80, 84, 84, 80, 84, 80, 82, 80, 84, 
          82, 80, 80, 80, 84, 80, -1, 80, 80, 80, 85, 80, 82, 83}),
/* NxS[  78] */ new Table(63, 51, -1, new short[] {207, -1, -1, -1, -1, -1, 
          206, 206, -1, -1, -1, 206, 206, -1, -1, -1, -1, -1, -1, -1, -1, 206, 
          206, -1, -1, -1, -1, -1, -1, -1, 206, 206, -1, 206, -1, 206, -1, 206, 
          206, -1, -1, -1, 206, -1, -1, -1, -1, -1, 207, -1, 206}),
/* NxS[  79] */ new Table(1, 46, 58, new short[] {76, 76, 58, 58, 58, 76, 
          77, 58, 58, 58, 58, 58, 58, 58, 58, 76, 76, 58, 58, 58, 78, 58, 
          58, 58, 79, 79, 58, 79, 58, 76, 58, 79, 76, 58, 58, 58, 79, 58, 
          -1, 58, 58, 58, 58, 58, 77, 78}),
/* NxS[  80] */ new Table(0, 0, -1, null),
/* NxS[  81] */ new Table(1, 45, 80, new short[] {81, 81, 80, 80, 80, 81, 
          81, 80, 80, 80, 80, 80, 80, 80, 80, 81, 81, 80, 80, 80, 80, 80, 
          80, 80, 81, 81, 80, 81, 80, 81, 80, 81, 81, 80, 80, 80, 81, 80, 
          -1, 80, 80, 80, 80, 80, 81}),
/* NxS[  82] */ new Table(1, 46, 80, new short[] {82, 82, 80, 80, 80, 82, 
          82, 80, 80, 80, 80, 80, 80, 80, 80, 82, 82, 80, 80, 80, 83, 80, 
          80, 80, 82, 82, 80, 82, 80, 82, 80, 82, 82, 80, 80, 80, 82, 80, 
          -1, 80, 80, 80, 80, 80, 82, 83}),
/* NxS[  83] */ new Table(63, 51, -1, new short[] {207, -1, -1, -1, -1, -1, 
          206, 206, -1, -1, -1, 206, 206, -1, -1, -1, -1, -1, -1, -1, -1, 206, 
          206, -1, -1, -1, -1, -1, -1, -1, 206, 206, -1, 206, -1, 206, -1, 206, 
          206, -1, -1, -1, 206, -1, -1, -1, -1, -1, 207, -1, 206}),
/* NxS[  84] */ new Table(1, 46, 58, new short[] {76, 76, 58, 58, 58, 76, 
          76, 58, 58, 58, 58, 58, 58, 58, 58, 76, 76, 58, 58, 58, 78, 58, 
          58, 58, 86, 86, 58, 86, 58, 76, 58, 86, 76, 58, 58, 58, 86, 58, 
          -1, 58, 58, 58, 58, 58, 76, 78}),
/* NxS[  85] */ new Table(25, 13, -1, new short[] {201, 201, -1, 201, -1, -1, 
          -1, 201, -1, -1, -1, -1, 201}),
/* NxS[  86] */ new Table(1, 46, 58, new short[] {76, 76, 58, 58, 58, 76, 
          76, 58, 58, 58, 58, 58, 58, 58, 58, 76, 76, 58, 58, 58, 78, 58, 
          58, 58, 86, 86, 58, 86, 58, 76, 58, 86, 76, 58, 58, 58, 86, 58, 
          -1, 58, 58, 58, 58, 58, 76, 78}),
/* NxS[  87] */ new Table(0, 0, -1, null),
/* NxS[  88] */ new Table(0, 0, -1, null),
/* NxS[  89] */ new Table(0, 0, -1, null),
/* NxS[  90] */ new Table(39, 1, 90, new short[] {-1}),
/* NxS[  91] */ new Table(0, 0, -1, null),
/* NxS[  92] */ new Table(0, 0, -1, null),
/* NxS[  93] */ new Table(34, 1, -1, new short[] {94}),
/* NxS[  94] */ new Table(0, 0, -1, null),
/* NxS[  95] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[  96] */ new Table(1, 45, -1, new short[] {203, 203, -1, -1, -1, 203, 
          203, -1, -1, -1, -1, -1, -1, -1, -1, 203, 203, -1, -1, -1, -1, -1, 
          -1, -1, 203, 203, -1, 203, -1, 203, -1, 203, 203, -1, -1, -1, 203, -1, 
          -1, -1, -1, -1, -1, -1, 203}),
/* NxS[  97] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[  98] */ new Table(63, 52, 80, new short[] {85, 80, 80, 80, 80, 80, 
          95, 95, 80, 80, 80, 95, 95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 
          95, 80, 80, 80, 83, 80, 80, 80, 110, 110, 80, 110, 80, 95, 80, 110, 
          95, 80, 80, 80, 110, 80, -1, 80, 80, 80, 85, 96, 95, 83}),
/* NxS[  99] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 103, 103, 104, 105, 101, 97, 58, 103, 97, 58, 58, 58, 103, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[ 100] */ new Table(25, 13, -1, new short[] {108, 108, 220, 108, -1, -1, 
          -1, 108, -1, -1, -1, -1, 108}),
/* NxS[ 101] */ new Table(0, 0, -1, null),
/* NxS[ 102] */ new Table(1, 45, -1, new short[] {203, 203, -1, -1, -1, 203, 
          203, -1, -1, -1, -1, -1, -1, -1, -1, 203, 203, -1, -1, -1, -1, -1, 
          -1, -1, 204, 204, -1, 204, -1, 203, -1, 204, 203, -1, -1, -1, 204, -1, 
          -1, -1, -1, -1, -1, -1, 203}),
/* NxS[ 103] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 106, 106, 104, 106, 58, 97, 58, 106, 97, 58, 58, 58, 106, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[ 104] */ new Table(25, 13, -1, new short[] {107, 107, 219, 107, -1, -1, 
          -1, 107, -1, -1, -1, -1, 107}),
/* NxS[ 105] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 106, 106, 104, 106, 58, 97, 58, 106, 97, 58, 58, 58, 106, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[ 106] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 106, 106, 104, 106, 101, 97, 58, 106, 97, 58, 58, 58, 106, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[ 107] */ new Table(25, 13, -1, new short[] {107, 107, 219, 107, 101, -1, 
          -1, 107, -1, -1, -1, -1, 107}),
/* NxS[ 108] */ new Table(25, 13, -1, new short[] {219, 219, 219, 109, 101, -1, 
          -1, 219, -1, -1, -1, -1, 219}),
/* NxS[ 109] */ new Table(25, 13, -1, new short[] {107, 107, 219, 107, -1, -1, 
          -1, 107, -1, -1, -1, -1, 107}),
/* NxS[ 110] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          97, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 111, 111, 58, 111, 58, 97, 58, 111, 97, 58, 58, 58, 111, 58, 
          -1, 58, 58, 58, 58, 112, 97, 78}),
/* NxS[ 111] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          97, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 111, 111, 58, 111, 58, 97, 58, 111, 97, 58, 58, 58, 111, 58, 
          -1, 58, 58, 58, 58, 112, 97, 78}),
/* NxS[ 112] */ new Table(1, 45, -1, new short[] {203, 203, -1, -1, -1, 203, 
          203, -1, -1, -1, -1, -1, -1, -1, -1, 203, 203, -1, -1, -1, -1, -1, 
          -1, -1, 203, 203, -1, 203, -1, 203, -1, 203, 203, -1, -1, -1, 203, -1, 
          -1, -1, -1, -1, -1, -1, 203}),
/* NxS[ 113] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 113, 114, 123, 113, 101, 97, 58, 113, 97, 58, 58, 58, 113, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[ 114] */ new Table(1, 46, 58, new short[] {97, 97, 58, 58, 58, 97, 
          98, 58, 58, 58, 58, 58, 58, 58, 58, 97, 97, 58, 58, 58, 78, 58, 
          58, 58, 114, 114, 58, 114, 58, 97, 58, 114, 97, 58, 58, 58, 114, 58, 
          -1, 58, 58, 58, 58, 102, 98, 78}),
/* NxS[ 115] */ new Table(1, 45, -1, new short[] {120, 120, -1, -1, -1, 120, 
          120, -1, -1, -1, -1, -1, -1, -1, -1, 120, 120, -1, -1, -1, -1, -1, 
          -1, -1, 120, 120, -1, 120, -1, 120, -1, 120, 120, -1, -1, -1, 120, -1, 
          -1, -1, -1, -1, -1, 222, 120}),
/* NxS[ 116] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 117, 95, 80, 117, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 117] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 117, 95, 118, 117, 101, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 118] */ new Table(25, 4, -1, new short[] {119, -1, 221, 119}),
/* NxS[ 119] */ new Table(25, 5, -1, new short[] {119, -1, 221, 119, 101}),
/* NxS[ 120] */ new Table(1, 46, 80, new short[] {120, 120, 80, 80, 80, 120, 
          120, 80, 80, 80, 80, 80, 80, 80, 80, 120, 120, 80, 80, 80, 83, 80, 
          80, 80, 120, 120, 121, 120, 101, 120, 80, 120, 120, 80, 80, 80, 120, 80, 
          -1, 80, 80, 80, 80, 96, 120, 83}),
/* NxS[ 121] */ new Table(1, 45, -1, new short[] {122, 122, -1, -1, -1, 122, 
          122, -1, -1, -1, -1, -1, -1, -1, -1, 122, 122, -1, -1, -1, -1, -1, 
          -1, -1, 122, 122, 223, 122, -1, 122, -1, 122, 122, -1, -1, -1, 122, -1, 
          -1, -1, -1, -1, -1, -1, 122}),
/* NxS[ 122] */ new Table(1, 45, -1, new short[] {122, 122, -1, -1, -1, 122, 
          122, -1, -1, -1, -1, -1, -1, -1, -1, 122, 122, -1, -1, -1, -1, -1, 
          -1, -1, 122, 122, 223, 122, 101, 122, -1, 122, 122, -1, -1, -1, 122, -1, 
          -1, -1, -1, -1, -1, -1, 122}),
/* NxS[ 123] */ new Table(25, 13, -1, new short[] {124, -1, 224, 124, -1, -1, 
          -1, 124, -1, -1, -1, -1, 124}),
/* NxS[ 124] */ new Table(25, 13, -1, new short[] {124, -1, 224, 124, 101, -1, 
          -1, 124, -1, -1, -1, -1, 124}),
/* NxS[ 125] */ new Table(0, 0, -1, null),
/* NxS[ 126] */ new Table(0, 0, -1, null),
/* NxS[ 127] */ new Table(0, 0, -1, null),
/* NxS[ 128] */ new Table(0, 0, -1, null),
/* NxS[ 129] */ new Table(0, 0, -1, null),
/* NxS[ 130] */ new Table(0, 0, -1, null),
/* NxS[ 131] */ new Table(0, 0, -1, null),
/* NxS[ 132] */ new Table(0, 0, -1, null),
/* NxS[ 133] */ new Table(5, 1, -1, new short[] {139}),
/* NxS[ 134] */ new Table(8, 1, -1, new short[] {260}),
/* NxS[ 135] */ new Table(10, 1, -1, new short[] {257}),
/* NxS[ 136] */ new Table(9, 1, -1, new short[] {259}),
/* NxS[ 137] */ new Table(0, 0, -1, null),
/* NxS[ 138] */ new Table(0, 0, -1, null),
/* NxS[ 139] */ new Table(0, 0, -1, null),
/* NxS[ 140] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 143, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 141] */ new Table(15, 1, -1, new short[] {262}),
/* NxS[ 142] */ new Table(0, 0, -1, null),
/* NxS[ 143] */ new Table(1, 46, 80, new short[] {144, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 144] */ new Table(1, 46, 80, new short[] {95, 95, 80, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 145, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 145] */ new Table(9, 1, -1, new short[] {265}),
/* NxS[ 146] */ new Table(0, 0, -1, null),
/* NxS[ 147] */ new Table(0, 0, -1, null),
/* NxS[ 148] */ new Table(0, 0, -1, null),
/* NxS[ 149] */ new Table(0, 0, -1, null),
/* NxS[ 150] */ new Table(7, 1, -1, new short[] {278}),
/* NxS[ 151] */ new Table(0, 0, -1, null),
/* NxS[ 152] */ new Table(0, 0, -1, null),
/* NxS[ 153] */ new Table(0, 0, -1, null),
/* NxS[ 154] */ new Table(0, 0, -1, null),
/* NxS[ 155] */ new Table(0, 0, -1, null),
/* NxS[ 156] */ new Table(3, 1, -1, new short[] {301}),
/* NxS[ 157] */ new Table(15, 1, -1, new short[] {300}),
/* NxS[ 158] */ new Table(4, 1, -1, new short[] {296}),
/* NxS[ 159] */ new Table(0, 0, -1, null),
/* NxS[ 160] */ new Table(0, 0, -1, null),
/* NxS[ 161] */ new Table(0, 0, -1, null),
/* NxS[ 162] */ new Table(1, 46, 80, new short[] {95, 95, 170, 171, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 163] */ new Table(10, 1, -1, new short[] {305}),
/* NxS[ 164] */ new Table(1, 1, -1, new short[] {303}),
/* NxS[ 165] */ new Table(1, 1, -1, new short[] {302}),
/* NxS[ 166] */ new Table(0, 0, -1, null),
/* NxS[ 167] */ new Table(0, 0, -1, null),
/* NxS[ 168] */ new Table(0, 0, -1, null),
/* NxS[ 169] */ new Table(0, 0, -1, null),
/* NxS[ 170] */ new Table(7, 1, -1, new short[] {173}),
/* NxS[ 171] */ new Table(6, 1, -1, new short[] {311}),
/* NxS[ 172] */ new Table(0, 0, -1, null),
/* NxS[ 173] */ new Table(0, 0, -1, null),
/* NxS[ 174] */ new Table(0, 0, -1, null),
/* NxS[ 175] */ new Table(0, 0, -1, null),
/* NxS[ 176] */ new Table(3, 1, -1, new short[] {177}),
/* NxS[ 177] */ new Table(0, 0, -1, null),
/* NxS[ 178] */ new Table(0, 0, -1, null),
/* NxS[ 179] */ new Table(0, 0, -1, null),
/* NxS[ 180] */ new Table(0, 0, -1, null),
/* NxS[ 181] */ new Table(0, 0, -1, null),
/* NxS[ 182] */ new Table(0, 0, -1, null),
/* NxS[ 183] */ new Table(0, 0, -1, null),
/* NxS[ 184] */ new Table(0, 0, -1, null),
/* NxS[ 185] */ new Table(0, 0, -1, null),
/* NxS[ 186] */ new Table(7, 1, -1, new short[] {361}),
/* NxS[ 187] */ new Table(8, 1, -1, new short[] {357}),
/* NxS[ 188] */ new Table(4, 1, -1, new short[] {356}),
/* NxS[ 189] */ new Table(0, 0, -1, null),
/* NxS[ 190] */ new Table(0, 0, -1, null),
/* NxS[ 191] */ new Table(0, 0, -1, null),
/* NxS[ 192] */ new Table(1, 46, 80, new short[] {95, 95, 195, 80, 80, 95, 
          95, 80, 80, 80, 80, 80, 80, 80, 80, 95, 95, 80, 80, 80, 83, 80, 
          80, 80, 95, 95, 80, 95, 80, 95, 80, 95, 95, 80, 80, 80, 95, 80, 
          -1, 80, 80, 80, 80, 96, 95, 83}),
/* NxS[ 193] */ new Table(3, 1, -1, new short[] {363}),
/* NxS[ 194] */ new Table(0, 0, -1, null),
/* NxS[ 195] */ new Table(4, 1, -1, new short[] {366}),
/* NxS[ 196] */ new Table(0, 0, -1, null),
/* NxS[ 197] */ new Table(14, 65, 9, new short[] {12, 9, 13, 14, 9, 9, 
          15, 16, 17, 18, 9, 19, 20, 9, 20, 9, 21, 9, 20, 21, 22, 9, 
          9, 20, 9, 23, 1, 24, 25, 26, 27, 21, 9, 28, 29, 30, 31, 32, 
          33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}),
/* NxS[ 198] */ new Table(7, 39, 58, new short[] {59, 58, 58, 58, 58, 58, 
          58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 62, 62, 58, 62, 
          58, 58, 58, 62, 58, 58, 58, 58, 62, 58, -1, 58, 58, 58, 58, 63, 
          59}),
/* NxS[ 199] */ new Table(25, 13, -1, new short[] {200, 200, -1, 200, -1, -1, 
          -1, 200, -1, -1, -1, -1, 200}),
/* NxS[ 200] */ new Table(7, 39, 58, new short[] {59, 58, 58, 58, 58, 58, 
          58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 60, 60, 58, 60, 
          58, 58, 58, 60, 58, 58, 58, 58, 60, 58, -1, 58, 58, 58, 58, 58, 
          59}),
/* NxS[ 201] */ new Table(25, 15, 58, new short[] {61, 61, 58, 61, 58, 58, 
          58, 61, 58, 58, 58, 58, 61, 58, -1}),
/* NxS[ 202] */ new Table(25, 13, -1, new short[] {201, 201, -1, 201, -1, -1, 
          -1, 201, -1, -1, -1, -1, 201}),
/* NxS[ 203] */ new Table(1, 46, 80, new short[] {82, 82, 80, 80, 80, 82, 
          82, 80, 80, 80, 80, 80, 80, 80, 80, 82, 82, 80, 80, 80, 83, 80, 
          80, 80, 82, 82, 80, 82, 80, 82, 80, 82, 82, 80, 80, 80, 82, 80, 
          -1, 80, 80, 80, 80, 80, 82, 83}),
/* NxS[ 204] */ new Table(1, 46, 58, new short[] {76, 76, 58, 58, 58, 76, 
          77, 58, 58, 58, 58, 58, 58, 58, 58, 76, 76, 58, 58, 58, 78, 58, 
          58, 58, 79, 79, 58, 79, 58, 76, 58, 79, 76, 58, 58, 58, 79, 58, 
          -1, 58, 58, 58, 58, 58, 77, 78}),
/* NxS[ 205] */ new Table(44, 1, -1, new short[] {75}),
/* NxS[ 206] */ new Table(1, 45, 80, new short[] {81, 81, 80, 80, 80, 81, 
          81, 80, 80, 80, 80, 80, 80, 80, 80, 81, 81, 80, 80, 80, 80, 80, 
          80, 80, 81, 81, 80, 81, 80, 81, 80, 81, 81, 80, 80, 80, 81, 80, 
          -1, 80, 80, 80, 80, 80, 81}),
/* NxS[ 207] */ new Table(1, 45, -1, new short[] {206, 206, -1, -1, -1, 206, 
          206, -1, -1, -1, -1, -1, -1, -1, -1, 206, 206, -1, -1, -1, -1, -1, 
          -1, -1, 206, 206, -1, 206, -1, 206, -1, 206, 206, -1, -1, -1, 206, -1, 
          -1, -1, -1, -1, -1, -1, 206}),
/* NxS[ 208] */ new Table(42, 1, 208, new short[] {209}),
/* NxS[ 209] */ new Table(41, 2, 208, new short[] {210, 209}),
/* NxS[ 210] */ new Table(39, 1, 92, new short[] {-1}),
/* NxS[ 211] */ new Table(34, 1, -1, new short[] {94}),
/* NxS[ 212] */ new Table(2, 36, -1, new short[] {211, -1, 211, 211, -1, -1, 
          -1, -1, 211, -1, -1, -1, -1, 213, -1, 211, -1, -1, -1, -1, -1, -1, 
          -1, 215, -1, -1, 214, -1, -1, -1, 215, -1, 93, 211, 211, 214}),
/* NxS[ 213] */ new Table(1, 45, -1, new short[] {216, 216, -1, -1, -1, 216, 
          216, -1, -1, -1, -1, -1, -1, -1, -1, 216, 216, -1, -1, -1, -1, -1, 
          -1, -1, 216, 216, -1, 216, -1, 216, -1, 216, 216, -1, -1, -1, 216, -1, 
          -1, -1, -1, -1, -1, -1, 216}),
/* NxS[ 214] */ new Table(25, 13, -1, new short[] {215, -1, -1, 215, -1, -1, 
          -1, 215, -1, 94, -1, -1, 215}),
/* NxS[ 215] */ new Table(25, 13, -1, new short[] {211, -1, -1, 211, -1, -1, 
          -1, 211, -1, 94, -1, -1, 211}),
/* NxS[ 216] */ new Table(1, 45, -1, new short[] {217, 217, -1, -1, -1, 217, 
          217, -1, -1, -1, -1, -1, -1, -1, -1, 217, 217, -1, -1, -1, -1, -1, 
          -1, -1, 217, 217, -1, 217, -1, 217, -1, 217, 217, -1, -1, -1, 217, -1, 
          -1, -1, -1, -1, -1, -1, 217}),
/* NxS[ 217] */ new Table(1, 45, -1, new short[] {218, 218, -1, -1, -1, 218, 
          218, -1, -1, -1, -1, -1, -1, -1, -1, 218, 218, -1, -1, -1, -1, -1, 
          -1, -1, 218, 218, -1, 218, -1, 218, -1, 218, 218, -1, -1, -1, 218, -1, 
          -1, -1, -1, -1, -1, -1, 218}),
/* NxS[ 218] */ new Table(1, 45, -1, new short[] {211, 211, -1, -1, -1, 211, 
          211, -1, -1, -1, -1, -1, -1, -1, -1, 211, 211, -1, -1, -1, -1, -1, 
          -1, -1, 211, 211, -1, 211, -1, 211, -1, 211, 211, -1, -1, -1, 211, -1, 
          -1, -1, -1, -1, -1, -1, 211}),
/* NxS[ 219] */ new Table(25, 13, -1, new short[] {107, 107, 219, 107, -1, -1, 
          -1, 107, -1, -1, -1, -1, 107}),
/* NxS[ 220] */ new Table(25, 13, -1, new short[] {108, 108, 220, 108, -1, -1, 
          -1, 108, -1, -1, -1, -1, 108}),
/* NxS[ 221] */ new Table(25, 4, -1, new short[] {119, -1, 221, 119}),
/* NxS[ 222] */ new Table(1, 45, -1, new short[] {203, 203, -1, -1, -1, 203, 
          203, -1, -1, -1, -1, -1, -1, -1, -1, 203, 203, -1, -1, -1, -1, -1, 
          -1, -1, 203, 203, -1, 203, -1, 203, -1, 203, 203, -1, -1, -1, 203, -1, 
          -1, -1, -1, -1, -1, -1, 203}),
/* NxS[ 223] */ new Table(1, 45, -1, new short[] {122, 122, -1, -1, -1, 122, 
          122, -1, -1, -1, -1, -1, -1, -1, -1, 122, 122, -1, -1, -1, -1, -1, 
          -1, -1, 122, 122, 223, 122, -1, 122, -1, 122, 122, -1, -1, -1, 122, -1, 
          -1, -1, -1, -1, -1, -1, 122}),
/* NxS[ 224] */ new Table(25, 13, -1, new short[] {124, -1, 224, 124, -1, -1, 
          -1, 124, -1, -1, -1, -1, 124}),
/* NxS[ 225] */ new Table(14, 1, -1, new short[] {226}),
/* NxS[ 226] */ new Table(9, 1, -1, new short[] {227}),
/* NxS[ 227] */ new Table(7, 1, -1, new short[] {125}),
/* NxS[ 228] */ new Table(9, 6, -1, new short[] {229, -1, -1, -1, -1, 230}),
/* NxS[ 229] */ new Table(1, 1, -1, new short[] {231}),
/* NxS[ 230] */ new Table(16, 1, -1, new short[] {126}),
/* NxS[ 231] */ new Table(4, 1, -1, new short[] {232}),
/* NxS[ 232] */ new Table(14, 1, -1, new short[] {233}),
/* NxS[ 233] */ new Table(9, 1, -1, new short[] {234}),
/* NxS[ 234] */ new Table(7, 1, -1, new short[] {127}),
/* NxS[ 235] */ new Table(6, 1, -1, new short[] {251}),
/* NxS[ 236] */ new Table(8, 7, -1, new short[] {241, -1, -1, -1, -1, -1, 
          242}),
/* NxS[ 237] */ new Table(2, 1, -1, new short[] {238}),
/* NxS[ 238] */ new Table(9, 1, -1, new short[] {239}),
/* NxS[ 239] */ new Table(14, 1, -1, new short[] {240}),
/* NxS[ 240] */ new Table(6, 1, -1, new short[] {128}),
/* NxS[ 241] */ new Table(4, 1, -1, new short[] {246}),
/* NxS[ 242] */ new Table(22, 1, -1, new short[] {243}),
/* NxS[ 243] */ new Table(1, 1, -1, new short[] {244}),
/* NxS[ 244] */ new Table(4, 1, -1, new short[] {245}),
/* NxS[ 245] */ new Table(7, 1, -1, new short[] {129}),
/* NxS[ 246] */ new Table(7, 1, -1, new short[] {247}),
/* NxS[ 247] */ new Table(6, 1, -1, new short[] {248}),
/* NxS[ 248] */ new Table(4, 1, -1, new short[] {249}),
/* NxS[ 249] */ new Table(7, 1, -1, new short[] {250}),
/* NxS[ 250] */ new Table(16, 1, -1, new short[] {130}),
/* NxS[ 251] */ new Table(11, 1, -1, new short[] {252}),
/* NxS[ 252] */ new Table(1, 1, -1, new short[] {253}),
/* NxS[ 253] */ new Table(20, 1, -1, new short[] {254}),
/* NxS[ 254] */ new Table(7, 1, -1, new short[] {131}),
/* NxS[ 255] */ new Table(4, 1, -1, new short[] {256}),
/* NxS[ 256] */ new Table(8, 1, -1, new short[] {132}),
/* NxS[ 257] */ new Table(1, 1, -1, new short[] {258}),
/* NxS[ 258] */ new Table(9, 1, -1, new short[] {136}),
/* NxS[ 259] */ new Table(12, 1, -1, new short[] {137}),
/* NxS[ 260] */ new Table(1, 1, -1, new short[] {261}),
/* NxS[ 261] */ new Table(4, 1, -1, new short[] {138}),
/* NxS[ 262] */ new Table(2, 1, -1, new short[] {263}),
/* NxS[ 263] */ new Table(9, 1, -1, new short[] {264}),
/* NxS[ 264] */ new Table(7, 1, -1, new short[] {142}),
/* NxS[ 265] */ new Table(4, 1, -1, new short[] {146}),
/* NxS[ 266] */ new Table(3, 2, -1, new short[] {277, 150}),
/* NxS[ 267] */ new Table(21, 1, -1, new short[] {268}),
/* NxS[ 268] */ new Table(8, 2, -1, new short[] {269, 270}),
/* NxS[ 269] */ new Table(5, 1, -1, new short[] {276}),
/* NxS[ 270] */ new Table(7, 1, -1, new short[] {271}),
/* NxS[ 271] */ new Table(18, 1, -1, new short[] {272}),
/* NxS[ 272] */ new Table(7, 1, -1, new short[] {273}),
/* NxS[ 273] */ new Table(10, 1, -1, new short[] {274}),
/* NxS[ 274] */ new Table(4, 1, -1, new short[] {275}),
/* NxS[ 275] */ new Table(3, 1, -1, new short[] {148}),
/* NxS[ 276] */ new Table(4, 1, -1, new short[] {149}),
/* NxS[ 277] */ new Table(4, 1, -1, new short[] {283}),
/* NxS[ 278] */ new Table(5, 1, -1, new short[] {279}),
/* NxS[ 279] */ new Table(17, 1, -1, new short[] {280}),
/* NxS[ 280] */ new Table(1, 1, -1, new short[] {281}),
/* NxS[ 281] */ new Table(6, 1, -1, new short[] {282}),
/* NxS[ 282] */ new Table(7, 1, -1, new short[] {151}),
/* NxS[ 283] */ new Table(1, 1, -1, new short[] {284}),
/* NxS[ 284] */ new Table(10, 1, -1, new short[] {285}),
/* NxS[ 285] */ new Table(6, 1, -1, new short[] {286}),
/* NxS[ 286] */ new Table(7, 1, -1, new short[] {287}),
/* NxS[ 287] */ new Table(8, 1, -1, new short[] {288}),
/* NxS[ 288] */ new Table(17, 1, -1, new short[] {152}),
/* NxS[ 289] */ new Table(4, 1, -1, new short[] {291}),
/* NxS[ 290] */ new Table(23, 1, -1, new short[] {153}),
/* NxS[ 291] */ new Table(14, 1, -1, new short[] {292}),
/* NxS[ 292] */ new Table(22, 1, -1, new short[] {293}),
/* NxS[ 293] */ new Table(7, 1, -1, new short[] {154}),
/* NxS[ 294] */ new Table(10, 1, -1, new short[] {295}),
/* NxS[ 295] */ new Table(20, 1, -1, new short[] {155}),
/* NxS[ 296] */ new Table(7, 1, -1, new short[] {297}),
/* NxS[ 297] */ new Table(10, 1, -1, new short[] {298}),
/* NxS[ 298] */ new Table(16, 1, -1, new short[] {299}),
/* NxS[ 299] */ new Table(3, 1, -1, new short[] {159}),
/* NxS[ 300] */ new Table(18, 1, -1, new short[] {160}),
/* NxS[ 301] */ new Table(7, 1, -1, new short[] {161}),
/* NxS[ 302] */ new Table(5, 1, -1, new short[] {166}),
/* NxS[ 303] */ new Table(3, 1, -1, new short[] {304}),
/* NxS[ 304] */ new Table(3, 1, -1, new short[] {167}),
/* NxS[ 305] */ new Table(3, 2, -1, new short[] {306, 307}),
/* NxS[ 306] */ new Table(4, 1, -1, new short[] {169}),
/* NxS[ 307] */ new Table(14, 1, -1, new short[] {308}),
/* NxS[ 308] */ new Table(10, 1, -1, new short[] {309}),
/* NxS[ 309] */ new Table(15, 1, -1, new short[] {310}),
/* NxS[ 310] */ new Table(7, 1, -1, new short[] {168}),
/* NxS[ 311] */ new Table(13, 1, -1, new short[] {172}),
/* NxS[ 312] */ new Table(4, 1, -1, new short[] {313}),
/* NxS[ 313] */ new Table(15, 1, -1, new short[] {314}),
/* NxS[ 314] */ new Table(5, 1, -1, new short[] {315}),
/* NxS[ 315] */ new Table(10, 1, -1, new short[] {174}),
/* NxS[ 316] */ new Table(1, 12, -1, new short[] {321, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 178}),
/* NxS[ 317] */ new Table(5, 10, -1, new short[] {318, -1, -1, -1, -1, -1, 
          -1, -1, -1, 319}),
/* NxS[ 318] */ new Table(8, 1, -1, new short[] {320}),
/* NxS[ 319] */ new Table(3, 1, -1, new short[] {175}),
/* NxS[ 320] */ new Table(23, 1, -1, new short[] {176}),
/* NxS[ 321] */ new Table(10, 1, -1, new short[] {322}),
/* NxS[ 322] */ new Table(3, 1, -1, new short[] {323}),
/* NxS[ 323] */ new Table(14, 1, -1, new short[] {324}),
/* NxS[ 324] */ new Table(7, 1, -1, new short[] {325}),
/* NxS[ 325] */ new Table(10, 1, -1, new short[] {326}),
/* NxS[ 326] */ new Table(4, 1, -1, new short[] {179}),
/* NxS[ 327] */ new Table(1, 5, -1, new short[] {348, -1, -1, -1, 349}),
/* NxS[ 328] */ new Table(10, 1, -1, new short[] {339}),
/* NxS[ 329] */ new Table(8, 1, -1, new short[] {337}),
/* NxS[ 330] */ new Table(21, 1, -1, new short[] {335}),
/* NxS[ 331] */ new Table(14, 1, -1, new short[] {332}),
/* NxS[ 332] */ new Table(4, 1, -1, new short[] {333}),
/* NxS[ 333] */ new Table(6, 1, -1, new short[] {334}),
/* NxS[ 334] */ new Table(13, 1, -1, new short[] {180}),
/* NxS[ 335] */ new Table(7, 1, -1, new short[] {336}),
/* NxS[ 336] */ new Table(5, 1, -1, new short[] {181}),
/* NxS[ 337] */ new Table(5, 1, -1, new short[] {338}),
/* NxS[ 338] */ new Table(4, 1, -1, new short[] {182}),
/* NxS[ 339] */ new Table(6, 1, -1, new short[] {340}),
/* NxS[ 340] */ new Table(13, 1, -1, new short[] {341}),
/* NxS[ 341] */ new Table(5, 1, -1, new short[] {342}),
/* NxS[ 342] */ new Table(8, 1, -1, new short[] {343}),
/* NxS[ 343] */ new Table(10, 1, -1, new short[] {344}),
/* NxS[ 344] */ new Table(14, 1, -1, new short[] {345}),
/* NxS[ 345] */ new Table(24, 1, -1, new short[] {346}),
/* NxS[ 346] */ new Table(7, 1, -1, new short[] {347}),
/* NxS[ 347] */ new Table(16, 1, -1, new short[] {183}),
/* NxS[ 348] */ new Table(4, 1, -1, new short[] {354}),
/* NxS[ 349] */ new Table(14, 1, -1, new short[] {350}),
/* NxS[ 350] */ new Table(6, 1, -1, new short[] {351}),
/* NxS[ 351] */ new Table(4, 1, -1, new short[] {352}),
/* NxS[ 352] */ new Table(17, 1, -1, new short[] {353}),
/* NxS[ 353] */ new Table(21, 1, -1, new short[] {184}),
/* NxS[ 354] */ new Table(14, 1, -1, new short[] {355}),
/* NxS[ 355] */ new Table(6, 1, -1, new short[] {185}),
/* NxS[ 356] */ new Table(7, 1, -1, new short[] {189}),
/* NxS[ 357] */ new Table(9, 1, -1, new short[] {358}),
/* NxS[ 358] */ new Table(7, 1, -1, new short[] {359}),
/* NxS[ 359] */ new Table(1, 1, -1, new short[] {360}),
/* NxS[ 360] */ new Table(10, 1, -1, new short[] {190}),
/* NxS[ 361] */ new Table(1, 1, -1, new short[] {362}),
/* NxS[ 362] */ new Table(11, 1, -1, new short[] {191}),
/* NxS[ 363] */ new Table(7, 1, -1, new short[] {364}),
/* NxS[ 364] */ new Table(5, 1, -1, new short[] {365}),
/* NxS[ 365] */ new Table(4, 1, -1, new short[] {194}),
/* NxS[ 366] */ new Table(5, 1, -1, new short[] {367}),
/* NxS[ 367] */ new Table(1, 1, -1, new short[] {368}),
/* NxS[ 368] */ new Table(6, 1, -1, new short[] {369}),
/* NxS[ 369] */ new Table(4, 1, -1, new short[] {196}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 68;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     public Scanner(Stream file) {
            SetSource(file, 0); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     public Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1:
/* ignore other whitespace */

/* 3.7 InputElement -> Comments */
            break;
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
        case 11:
        case 12:
        case 13:
        case 14:
        case 15:
        case 16:
        case 17:
        case 18:
        case 21:
        case 22:
throw new Exception(String.Format("unexpected character '{0}'", yytext));
            break;
        case 19:
        case 20:
        case 99:
        case 101:
        case 105:
        case 106:
        case 107:
        case 108:
        case 109:
        case 113:
        case 117:
        case 119:
        case 120:
        case 122:
        case 124:
yylval.name = yytext; return (int)Tokens.IntergerLiteral;
            break;
        case 23:
lines++;
            break;
        case 24:
return '/';
            break;
        case 25:
return '*';
            break;
        case 26:
return '+';
            break;
        case 27:
return '.';
            break;
        case 28:
return '(';
            break;
        case 29:
return ')';
            break;
        case 30:
return '{';
            break;
        case 31:
return '}';
            break;
        case 32:
return '[';
            break;
        case 33:
return ']';
            break;
        case 34:
return ';';
            break;
        case 35:
return ',';
            break;
        case 36:
return '@';
            break;
        case 37:
return ':';
            break;
        case 38:
return '=';
            break;
        case 39:
return '<';
            break;
        case 40:
return '>';
            break;
        case 41:
return '!';
            break;
        case 42:
return '~';
            break;
        case 43:
return '?';
            break;
        case 44:
return '-';
            break;
        case 45:
return '&';
            break;
        case 46:
return '|';
            break;
        case 47:
return '^';
            break;
        case 48:
return '%';
            break;
        case 49:
return (int)Tokens.ModulusAnd;
            break;
        case 50:
return (int)Tokens.BitwiseExclusiveOr;
            break;
        case 51:
return (int)Tokens.BitwiseInclusiveOr;
            break;
        case 52:
return (int)Tokens.CONDITION_OR;
            break;
        case 53:
return (int)Tokens.BITWISE_AND;
            break;
        case 54:
return (int)Tokens.CONDITION_AND;
            break;
        case 55:
return (int)Tokens.SUBTRACT_AND;
            break;
        case 56:
return (int)Tokens.SELECTION;
            break;
        case 57:
return (int)Tokens.DECREMENT;
            break;
        case 58:
        case 59:
        case 60:
        case 61:
        case 62:
        case 63:
        case 76:
        case 77:
        case 78:
        case 79:
        case 86:
        case 97:
        case 98:
        case 100:
        case 102:
        case 103:
        case 104:
        case 111:
        case 112:
        case 114:
        case 115:
        case 116:
        case 123:
yylval.name = yytext; return (int)Tokens.DecimalFloatingPointLiteral;
            break;
        case 64:
return (int)Tokens.NOT_EQUAL_TO;
            break;
        case 65:
return (int)Tokens.GREATER_THAN_OR_EQUAL_TO;
            break;
        case 66:
return (int)Tokens.SINGED_RIGHT_SHIFT;
            break;
        case 67:
return (int)Tokens.RightShiftAnd;
            break;
        case 68:
return (int)Tokens.UNSIGNED_RIGHT_SHFIT;
            break;
        case 69:
return (int)Tokens.ShiftRightZeroFill;
            break;
        case 70:
return (int)Tokens.LESS_THAN_OR_EUAL_TO;
            break;
        case 71:
return (int)Tokens.SINGED_LEFT_SHIFT;
            break;
        case 72:
return (int)Tokens.LeftShiftAnd;
            break;
        case 73:
return (int)Tokens.EUQL_TO;
            break;
        case 74:
return (int)Tokens.DoubleColon;
            break;
        case 75:
return (int)Tokens.VariableArguments;
            break;
        case 80:
        case 81:
        case 82:
        case 83:
        case 84:
        case 85:
        case 95:
        case 96:
        case 110:
        case 118:
        case 121:
        case 133:
        case 134:
        case 135:
        case 140:
        case 143:
        case 144:
        case 145:
        case 156:
        case 157:
        case 158:
        case 162:
        case 163:
        case 164:
        case 165:
        case 170:
        case 171:
        case 186:
        case 187:
        case 188:
        case 192:
        case 193:
        case 195:
yylval.name = yytext; return (int)Tokens.HexadecimalFloatingPointLiteral;
            break;
        case 87:
return (int)Tokens.INCREMENT;
            break;
        case 88:
return (int)Tokens.ADD_AND;
            break;
        case 89:
return (int)Tokens.MULTIPLY_AND;
            break;
        case 90:
/* skip single line comment */
            break;
        case 91:
return (int)Tokens.DIVIDE_AND;
            break;
        case 92:
/* skip multiline comment */

/*3.10.2. Floating-Point Literals*/
            break;
        case 93:
        case 94:
yylval.name = yytext; return (int)Tokens.CharacterLiteral;
            break;
        case 125:
return (int)Tokens.While;
            break;
        case 126:
return (int)Tokens.Void;
            break;
        case 127:
return (int)Tokens.Volatile;
            break;
        case 128:
return (int)Tokens.Public;
            break;
        case 129:
return (int)Tokens.Private;
            break;
        case 130:
return (int)Tokens.Protected;
            break;
        case 131:
return (int)Tokens.Package;
            break;
        case 132:
return (int)Tokens.Goto;
            break;
        case 136:
return (int)Tokens.Final;
            break;
        case 137:
return (int)Tokens.Finally;
            break;
        case 138:
return (int)Tokens.Float;
            break;
        case 139:
return (int)Tokens.For;
            break;
        case 141:
return (int)Tokens.Do;
            break;
        case 142:
return (int)Tokens.Double;
            break;
        case 146:
return (int)Tokens.Default;
            break;
        case 147:
return (int)Tokens.If;
            break;
        case 148:
return (int)Tokens.Implements;
            break;
        case 149:
return (int)Tokens.Import;
            break;
        case 150:
return (int)Tokens.Int;
            break;
        case 151:
return (int)Tokens.Interface;
            break;
        case 152:
return (int)Tokens.Instanceof;
            break;
        case 153:
return (int)Tokens.New;
            break;
        case 154:
return (int)Tokens.Native;
            break;
        case 155:
return (int)Tokens.Long;
            break;
        case 159:
return (int)Tokens.Extends;
            break;
        case 160:
return (int)Tokens.Enum;
            break;
        case 161:
return (int)Tokens.Else;
            break;
        case 166:
return (int)Tokens.Char;
            break;
        case 167:
return (int)Tokens.Class;
            break;
        case 168:
return (int)Tokens.Continue;
            break;
        case 169:
return (int)Tokens.Const;
            break;
        case 172:
return (int)Tokens.Catch;
            break;
        case 173:
return (int)Tokens.Case;
            break;
        case 174:
return (int)Tokens.Return;
            break;
        case 175:
return (int)Tokens.This;
            break;
        case 176:
return (int)Tokens.Throw;
            break;
        case 177:
return (int)Tokens.Throws;
            break;
        case 178:
return (int)Tokens.Try;
            break;
        case 179:
return (int)Tokens.Transient;
            break;
        case 180:
return (int)Tokens.Switch;
            break;
        case 181:
return (int)Tokens.Super;
            break;
        case 182:
return (int)Tokens.Short;
            break;
        case 183:
return (int)Tokens.Synchronized;
            break;
        case 184:
return (int)Tokens.Strictfp;
            break;
        case 185:
return (int)Tokens.Static;
            break;
        case 189:
return (int)Tokens.Byte;
            break;
        case 190:
return (int)Tokens.Boolean;
            break;
        case 191:
return (int)Tokens.Break;
            break;
        case 194:
return (int)Tokens.Assert;
            break;
        case 196:
return (int)Tokens.Abstract;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner

// ==============================================================
// <auto-generated>
// This code automatically produced from an embedded resource.
// Do not edit this file, or it will become incompatible with 
// the specification from which it was generated.
// </auto-generated>
// ==============================================================

// Code copied from GPLEX embedded resource
    [Serializable]
    public class BufferException : Exception
    {
        public BufferException() { }
        public BufferException(string message) : base(message) { }
        public BufferException(string message, Exception innerException)
            : base(message, innerException) { }
        protected BufferException(SerializationInfo info, StreamingContext context)
            : base(info, context) { }
    }

    public abstract class ScanBuff
    {
        private string fileNm;

        public const int EndOfFile = -1;
        public const int UnicodeReplacementChar = 0xFFFD;

        public bool IsFile { get { return (fileNm != null); } }
        public string FileName { get { return fileNm; } set { fileNm = value; } }

        public abstract int Pos { get; set; }
        public abstract int Read();
        public virtual void Mark() { }

        public abstract string GetString(int begin, int limit);

        public static ScanBuff GetBuffer(string source)
        {
            return new StringBuffer(source);
        }

        public static ScanBuff GetBuffer(IList<string> source)
        {
            return new LineBuffer(source);
        }

#if (!NOFILES)
        public static ScanBuff GetBuffer(Stream source)
        {
            return new BuildBuffer(source);
        }

#if (!BYTEMODE)
        public static ScanBuff GetBuffer(Stream source, int fallbackCodePage)
        {
            return new BuildBuffer(source, fallbackCodePage);
        }
#endif // !BYTEMODE
#endif // !NOFILES
    }

    #region Buffer classes

    // ==============================================================
    // =====  Definitions for various ScanBuff derived classes   ====
    // ==============================================================
    // ===============         String input          ================
    // ==============================================================

    /// <summary>
    /// This class reads characters from a single string as
    /// required, for example, by Visual Studio language services
    /// </summary>
    sealed class StringBuffer : ScanBuff
    {
        string str;        // input buffer
        int bPos;          // current position in buffer
        int sLen;

        public StringBuffer(string source)
        {
            this.str = source;
            this.sLen = source.Length;
            this.FileName = null;
        }

        public override int Read()
        {
            if (bPos < sLen) return str[bPos++];
            else if (bPos == sLen) { bPos++; return '\n'; }   // one strike, see new line
            else { bPos++; return EndOfFile; }                // two strikes and you're out!
        }

        public override string GetString(int begin, int limit)
        {
            //  "limit" can be greater than sLen with the BABEL
            //  option set.  Read returns a "virtual" EOL if
            //  an attempt is made to read past the end of the
            //  string buffer.  Without the guard any attempt 
            //  to fetch yytext for a token that includes the 
            //  EOL will throw an index exception.
            if (limit > sLen) limit = sLen;
            if (limit <= begin) return "";
            else return str.Substring(begin, limit - begin);
        }

        public override int Pos
        {
            get { return bPos; }
            set { bPos = value; }
        }

        public override string ToString() { return "StringBuffer"; }
    }

    // ==============================================================
    //  The LineBuff class contributed by Nigel Horspool, 
    //  nigelh@cs.uvic.cs
    // ==============================================================

    sealed class LineBuffer : ScanBuff
    {
        IList<string> line;    // list of source lines from a file
        int numLines;          // number of strings in line list
        string curLine;        // current line in that list
        int cLine;             // index of current line in the list
        int curLen;            // length of current line
        int curLineStart;      // position of line start in whole file
        int curLineEnd;        // position of line end in whole file
        int maxPos;            // max position ever visited in whole file
        int cPos;              // ordinal number of code in source

        // Constructed from a list of strings, one per source line.
        // The lines have had trailing '\n' characters removed.
        public LineBuffer(IList<string> lineList)
        {
            line = lineList;
            numLines = line.Count;
            cPos = curLineStart = 0;
            curLine = (numLines > 0 ? line[0] : "");
            maxPos = curLineEnd = curLen = curLine.Length;
            cLine = 1;
            FileName = null;
        }

        public override int Read()
        {
            if (cPos < curLineEnd)
                return curLine[cPos++ - curLineStart];
            if (cPos++ == curLineEnd)
                return '\n';
            if (cLine >= numLines)
                return EndOfFile;
            curLine = line[cLine];
            curLen = curLine.Length;
            curLineStart = curLineEnd + 1;
            curLineEnd = curLineStart + curLen;
            if (curLineEnd > maxPos)
                maxPos = curLineEnd;
            cLine++;
            return curLen > 0 ? curLine[0] : '\n';
        }

        // To speed up searches for the line containing a position
        private int cachedPosition;
        private int cachedIxdex;
        private int cachedLineStart;

        // Given a position pos within the entire source, the results are
        //   ix     -- the index of the containing line
        //   lstart -- the position of the first character on that line
        private void findIndex(int pos, out int ix, out int lstart)
        {
            if (pos >= cachedPosition)
            {
                ix = cachedIxdex; lstart = cachedLineStart;
            }
            else
            {
                ix = lstart = 0;
            }
            while (ix < numLines)
            {
                int len = line[ix].Length + 1;
                if (pos < lstart + len) break;
                lstart += len;
                ix++;
            }
            cachedPosition = pos;
            cachedIxdex = ix;
            cachedLineStart = lstart;
        }

        public override string GetString(int begin, int limit)
        {
            if (begin >= maxPos || limit <= begin) return "";
            int endIx, begIx, endLineStart, begLineStart;
            findIndex(begin, out begIx, out begLineStart);
            int begCol = begin - begLineStart;
            findIndex(limit, out endIx, out endLineStart);
            int endCol = limit - endLineStart;
            string s = line[begIx];
            if (begIx == endIx)
            {
                // the usual case, substring all on one line
                return (endCol <= s.Length) ?
                    s.Substring(begCol, endCol - begCol)
                    : s.Substring(begCol) + "\n";
            }
            // the string spans multiple lines, yuk!
            StringBuilder sb = new StringBuilder();
            if (begCol < s.Length)
                sb.Append(s.Substring(begCol));
            for (; ; )
            {
                sb.Append("\n");
                s = line[++begIx];
                if (begIx >= endIx) break;
                sb.Append(s);
            }
            if (endCol <= s.Length)
            {
                sb.Append(s.Substring(0, endCol));
            }
            else
            {
                sb.Append(s);
                sb.Append("\n");
            }
            return sb.ToString();
        }

        public override int Pos
        {
            get { return cPos; }
            set
            {
                cPos = value;
                findIndex(cPos, out cLine, out curLineStart);
                // cLine should be the *next* line after curLine.
                curLine = (cLine < numLines ? line[cLine++] : "");
                curLineEnd = curLineStart + curLine.Length;
            }
        }

        public override string ToString() { return "LineBuffer"; }
    }

#if (!NOFILES)
    // ==============================================================
    // =====     class BuildBuff : for unicode text files    ========
    // ==============================================================

    class BuildBuffer : ScanBuff
    {
        // Double buffer for char stream.
        class BufferElement
        {
            StringBuilder bldr = new StringBuilder();
            StringBuilder next = new StringBuilder();
            int minIx;
            int maxIx;
            int brkIx;
            bool appendToNext;

            internal BufferElement() { }

            internal int MaxIndex { get { return maxIx; } }
            // internal int MinIndex { get { return minIx; } }

            internal char this[int index]
            {
                get
                {
                    if (index < minIx || index >= maxIx)
                        throw new BufferException("Index was outside data buffer");
                    else if (index < brkIx)
                        return bldr[index - minIx];
                    else
                        return next[index - brkIx];
                }
            }

            internal void Append(char[] block, int count)
            {
                maxIx += count;
                if (appendToNext)
                    this.next.Append(block, 0, count);
                else
                {
                    this.bldr.Append(block, 0, count);
                    brkIx = maxIx;
                    appendToNext = true;
                }
            }

            internal string GetString(int start, int limit)
            {
                if (limit <= start)
                    return "";
                if (start >= minIx && limit <= maxIx)
                    if (limit < brkIx) // String entirely in bldr builder
                        return bldr.ToString(start - minIx, limit - start);
                    else if (start >= brkIx) // String entirely in next builder
                        return next.ToString(start - brkIx, limit - start);
                    else // Must do a string-concatenation
                        return
                            bldr.ToString(start - minIx, brkIx - start) +
                            next.ToString(0, limit - brkIx);
                else
                    throw new BufferException("String was outside data buffer");
            }

            internal void Mark(int limit)
            {
                if (limit > brkIx + 16) // Rotate blocks
                {
                    StringBuilder temp = bldr;
                    bldr = next;
                    next = temp;
                    next.Length = 0;
                    minIx = brkIx;
                    brkIx = maxIx;
                }
            }
        }

        BufferElement data = new BufferElement();

        int bPos;            // Postion index in the StringBuilder
        BlockReader NextBlk; // Delegate that serves char-arrays;

        private string EncodingName
        {
            get
            {
                StreamReader rdr = NextBlk.Target as StreamReader;
                return (rdr == null ? "raw-bytes" : rdr.CurrentEncoding.BodyName);
            }
        }

        public BuildBuffer(Stream stream)
        {
            FileStream fStrm = (stream as FileStream);
            if (fStrm != null) FileName = fStrm.Name;
            NextBlk = BlockReaderFactory.Raw(stream);
        }

#if (!BYTEMODE)
        public BuildBuffer(Stream stream, int fallbackCodePage)
        {
            FileStream fStrm = (stream as FileStream);
            if (fStrm != null) FileName = fStrm.Name;
            NextBlk = BlockReaderFactory.Get(stream, fallbackCodePage);
        }
#endif

        /// <summary>
        /// Marks a conservative lower bound for the buffer,
        /// allowing space to be reclaimed.  If an application 
        /// needs to call GetString at arbitrary past locations 
        /// in the input stream, Mark() is not called.
        /// </summary>
        public override void Mark() { data.Mark(bPos - 2); }

        public override int Pos
        {
            get { return bPos; }
            set { bPos = value; }
        }


        /// <summary>
        /// Read returns the ordinal number of the next char, or 
        /// EOF (-1) for an end of stream.  Note that the next
        /// code point may require *two* calls of Read().
        /// </summary>
        /// <returns></returns>
        public override int Read()
        {
            //
            //  Characters at positions 
            //  [data.offset, data.offset + data.bldr.Length)
            //  are available in data.bldr.
            //
            if (bPos < data.MaxIndex)
            {
                // ch0 cannot be EOF
                return (int)data[bPos++];
            }
            else // Read from underlying stream
            {
                // Experimental code, blocks of page size
                char[] chrs = new char[4096];
                int count = NextBlk(chrs, 0, 4096);
                if (count == 0)
                    return EndOfFile;
                else
                {
                    data.Append(chrs, count);
                    return (int)data[bPos++];
                }
            }
        }

        public override string GetString(int begin, int limit)
        {
            return data.GetString(begin, limit);
        }

        public override string ToString()
        {
            return "StringBuilder buffer, encoding: " + this.EncodingName;
        }
    }

    // =============== End ScanBuff-derived classes ==================

    public delegate int BlockReader(char[] block, int index, int number);

    // A delegate factory, serving up a delegate that
    // reads a block of characters from the underlying
    // encoded stream, via a StreamReader object.
    //
    public static class BlockReaderFactory
    {
        public static BlockReader Raw(Stream stream)
        {
            return delegate(char[] block, int index, int number)
            {
                byte[] b = new byte[number];
                int count = stream.Read(b, 0, number);
                int i = 0;
                int j = index;
                for (; i < count; i++, j++)
                    block[j] = (char)b[i];
                return count;
            };
        }

#if (!BYTEMODE)
        public static BlockReader Get(Stream stream, int fallbackCodePage)
        {
            Encoding encoding;
            int preamble = Preamble(stream);

            if (preamble != 0)  // There is a valid BOM here!
                encoding = Encoding.GetEncoding(preamble);
            else if (fallbackCodePage == -1) // Fallback is "raw" bytes
                return Raw(stream);
            else if (fallbackCodePage != -2) // Anything but "guess"
                encoding = Encoding.GetEncoding(fallbackCodePage);
            else // This is the "guess" option
            {
                int guess = new Guesser(stream).GuessCodePage();
                stream.Seek(0, SeekOrigin.Begin);
                if (guess == -1) // ==> this is a 7-bit file
                    encoding = Encoding.ASCII;
                else if (guess == 65001)
                    encoding = Encoding.UTF8;
                else             // ==> use the machine default
                    encoding = Encoding.Default;
            }
            StreamReader reader = new StreamReader(stream, encoding);
            return reader.Read;
        }

        static int Preamble(Stream stream)
        {
            int b0 = stream.ReadByte();
            int b1 = stream.ReadByte();

            if (b0 == 0xfe && b1 == 0xff)
                return 1201; // UTF16BE
            if (b0 == 0xff && b1 == 0xfe)
                return 1200; // UTF16LE

            int b2 = stream.ReadByte();
            if (b0 == 0xef && b1 == 0xbb && b2 == 0xbf)
                return 65001; // UTF8
            //
            // There is no unicode preamble, so we
            // return denoter for the machine default.
            //
            stream.Seek(0, SeekOrigin.Begin);
            return 0;
        }
#endif // !BYTEMODE
    }
#endif // !NOFILES
    #endregion Buffer classes

    // ==============================================================
    // ============      class CodePageHandling         =============
    // ==============================================================
#if (!NOFILES)
    public static class CodePageHandling
    {
        public static int GetCodePage(string option)
        {
            string command = option.ToUpperInvariant();
            if (command.StartsWith("CodePage:", StringComparison.OrdinalIgnoreCase))
                command = command.Substring(9);
            try
            {
                if (command.Equals("RAW"))
                    return -1;
                else if (command.Equals("GUESS"))
                    return -2;
                else if (command.Equals("DEFAULT"))
                    return 0;
                else if (char.IsDigit(command[0]))
                    return int.Parse(command, CultureInfo.InvariantCulture);
                else
                {
                    Encoding enc = Encoding.GetEncoding(command);
                    return enc.CodePage;
                }
            }
            catch (FormatException)
            {
                Console.Error.WriteLine(
                    "Invalid format \"{0}\", using machine default", option);
            }
            catch (ArgumentException)
            {
                Console.Error.WriteLine(
                    "Unknown code page \"{0}\", using machine default", option);
            }
            return 0;
        }
    }
#region guesser
#if (!BYTEMODE)
    // ==============================================================
    // ============          Encoding Guesser           =============
    // ==============================================================

    /// <summary>
    /// This class provides a simple finite state automaton that
    /// scans the file looking for (1) valid UTF-8 byte patterns,
    /// (2) bytes >= 0x80 which are not part of a UTF-8 sequence.
    /// The method then guesses whether it is UTF-8 or maybe some 
    /// local machine default encoding.  This works well for the
    /// various Latin encodings.
    /// </summary>
    internal class Guesser
    {
        ScanBuff buffer;

        public int GuessCodePage() { return Scan(); }

        const int maxAccept = 10;
        const int initial = 0;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int EndToken = 0;

        #region user code
        /* 
         *  Reads the bytes of a file to determine if it is 
         *  UTF-8 or a single-byte code page file.
         */
        public long utfX;
        public long uppr;
        #endregion user code

        int state;
        int currentStart = startState[0];
        int code;

        #region ScannerTables
        static int[] startState = new int[] { 11, 0 };

        #region CharacterMap
        static sbyte[] map = new sbyte[256] {
/*     '\0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x10' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x20' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '@' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'P' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '`' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'p' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x80' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x90' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xA0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xB0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xC0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xD0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xE0' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*   '\xF0' */ 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5 };
        #endregion

        static sbyte[][] nextState = new sbyte[][] {
            new sbyte[] {0, 0, 0, 0, 0, 0},
            new sbyte[] {-1, -1, 10, -1, -1, -1},
            new sbyte[] {-1, -1, -1, -1, -1, -1},
            new sbyte[] {-1, -1, 8, -1, -1, -1},
            new sbyte[] {-1, -1, 5, -1, -1, -1},
            new sbyte[] {-1, -1, 6, -1, -1, -1},
            new sbyte[] {-1, -1, 7, -1, -1, -1},
            null,
            new sbyte[] {-1, -1, 9, -1, -1, -1},
            null,
            null,
            new sbyte[] {-1, 1, 2, 3, 4, 2}
        };


        [SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
        // Reason for suppression: cannot have self-reference in array initializer.
        static Guesser()
        {
            nextState[7] = nextState[2];
            nextState[9] = nextState[2];
            nextState[10] = nextState[2];
        }

        int NextState()
        {
            if (code == ScanBuff.EndOfFile)
                return eofNum;
            else
                return nextState[state][map[code]];
        }
        #endregion

        public Guesser(System.IO.Stream file) { SetSource(file); }

        public void SetSource(System.IO.Stream source)
        {
            this.buffer = new BuildBuffer(source);
            code = buffer.Read();
        }

        int Scan()
        {
            for (; ; )
            {
                int next;
                state = currentStart;
                while ((next = NextState()) == goStart)
                    code = buffer.Read();

                state = next;
                code = buffer.Read();

                while ((next = NextState()) > eofNum)
                {
                    state = next;
                    code = buffer.Read();
                }
                if (state <= maxAccept)
                {
                    #region ActionSwitch
#pragma warning disable 162
                    switch (state)
                    {
                        case eofNum:
                            switch (currentStart)
                            {
                                case 11:
                                    if (utfX == 0 && uppr == 0) return -1; /* raw ascii */
                                    else if (uppr * 10 > utfX) return 0;   /* default code page */
                                    else return 65001;                     /* UTF-8 encoding */
                                    break;
                            }
                            return EndToken;
                        case 1: // Recognized '{Upper128}',	Shortest string "\xC0"
                        case 2: // Recognized '{Upper128}',	Shortest string "\x80"
                        case 3: // Recognized '{Upper128}',	Shortest string "\xE0"
                        case 4: // Recognized '{Upper128}',	Shortest string "\xF0"
                            uppr++;
                            break;
                        case 5: // Recognized '{Utf8pfx4}{Utf8cont}',	Shortest string "\xF0\x80"
                            uppr += 2;
                            break;
                        case 6: // Recognized '{Utf8pfx4}{Utf8cont}{2}',	Shortest string "\xF0\x80\x80"
                            uppr += 3;
                            break;
                        case 7: // Recognized '{Utf8pfx4}{Utf8cont}{3}',	Shortest string "\xF0\x80\x80\x80"
                            utfX += 3;
                            break;
                        case 8: // Recognized '{Utf8pfx3}{Utf8cont}',	Shortest string "\xE0\x80"
                            uppr += 2;
                            break;
                        case 9: // Recognized '{Utf8pfx3}{Utf8cont}{2}',	Shortest string "\xE0\x80\x80"
                            utfX += 2;
                            break;
                        case 10: // Recognized '{Utf8pfx2}{Utf8cont}',	Shortest string "\xC0\x80"
                            utfX++;
                            break;
                        default:
                            break;
                    }
#pragma warning restore 162
                    #endregion
                }
            }
        }
    } // end class Guesser
    
#endif // !BYTEMODE
#endregion
#endif // !NOFILES

// End of code copied from embedded resource

} // end namespace
